// *** Cutscene: Rogue appears from the portal to the north of Charname's cell - Part 1 ***

IF
  True()
THEN
  RESPONSE #100
    CutSceneId(Player1)
    CloseDoor("Door05")
    MoveViewPoint([3875.2445], INSTANT)
    CreateCreature("a7-ctspy", [3790.2450], 0)  // S
    Wait(2)
    CreateVisualEffect("SPCLOUD1", [3870.2456])
    CreateCreature("a7-shad1", [3870.2456], 2)  // SW
    Wait(2)
    StartCutScene("a7-cut02")
END
