// *** Adrian Sianodel by Rhaella (based on v3.1) ***

ACTION_IF (FILE_EXISTS_IN_GAME ~RH#ADR.CRE~) BEGIN
  OUTER_SET num_npc_actions = 1

  OUTER_TEXT_SPRINT npc_trigger_0
    ~!InParty("rh#Adrian")
     !BeenInParty("rh#Adrian")
     Global("rh#FirstTalk","GLOBAL",0)
     !Dead("duergar1")~

  OUTER_TEXT_SPRINT npc_action_0
    ~SetGlobal("SPRITE_IS_DEADduergar1","GLOBAL",1)
     CreateCreature("rh#adr",[2330.1070],E)
     GiveItemCreate("rh#key",Player1,0,0,0)~
END
